Master
danielskatz/software-vs-data pull request #23
Opened 2016-11-24 07:41 UTC by rwwh

Another attempt, now with references to documents on the web. My github experience is exhausted so I hope this will work.

2016-11-24 12:42 UTC, danielskatz commented
The GitHub part of this is fine, but I still have some issues with the context you want to add.

I will put specific comments in the PR.

2016-11-24 12:43 UTC, danielskatz commented on README.md
> +###Software is available in a human readable and separate computer readable form, data in only one of the two.
Data could also be in two forms, for example, ASCII and binary, or ASCII and something compressed.

2016-11-24 12:48 UTC, danielskatz commented on README.md
> +Especially software in traditional compiled programming languages consist in two forms: the *source code* and the *compiled code*. The transformation between the human readable source code and the ma
Regarding the first two sentences, data could also be available in 2 forms, though perhaps an irreversible transformation process would make less sense.

Regarding the third sentence, the license citation you give doesn't seem to be related to the fact that there is source code and compiled code. Rather, it is yet a third case (that I'm not sure I want to bring it up in this document) related to the discussion in "Software is a creative work, data are facts or observations" where we already talk about different licenses for software and data.  This reference says that neither of these types of licenses are right for data collections (basically databases containing data objects).  I can't see how this helps, either demonstrating the point in the first 2 sentences or in the overall document.

2016-11-24 12:50 UTC, danielskatz commented on README.md
> +Furthermore subtle differences between different compilers (e.g. on two different machines or two different operating systems) can result in subtly different results when the software is run on the s
I completely agree with the points you make here, but again I don't see what the difference between software and data is.  This says reproducibility is a hard problem, and that running the same software on the same data on a different system/environment can lead to a different result.  How does this show a difference between software and data?

2016-11-24 12:52 UTC, danielskatz requested changes
I appreciate your work in adding citations, but they do not convince me that your additional paragraph contributes to the differences between software and data.  I've added some detailed comments.  Please take a look and try to help me see why this addition makes the overall document stronger.

2016-11-25 15:42 UTC, rwwh commented
OK. Thanks, and good luck with the project.

2016-11-25 15:42 UTC, closed without merging

2016-11-27 15:00 UTC, danielskatz commented
I would still like to add you as an author, since you contributed this discussion.  Is this ok with you?

2016-11-27 15:40 UTC, band commented
Yes and thank you.

2016-11-27 16:00 UTC, danielskatz commented
Sorry, this was implicitly addressed to @rwwh since he was the person who suggested this change and did the work to explain it.

@band, you are already listed as an author based on a previous contribution.

2016-11-27 16:16 UTC, band commented
Ha ha ha. Gotta love a user's experience. I thought about the implicit recipient, but the web git UI fooled me.

2016-11-27 18:26 UTC, rwwh commented
Yes and thank you. ;-) ?

I really appreciate this project and certainly appreciate being able to attach my name to it.